#mapper:
#  mappers:
#    - tk.mybatis.mapper.common.Mapper
#  notEmpty: true
#  ORDER: BEFORE


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xxxx.mappertest
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置Oracle数据库
spring:
#  servlet:
#    multipart:
#      max-file-size: 500MB
#      max-request-size: 200MB
  datasource:
    url: jdbc:oracle:thin:@192.168.80.10:1521:orcl
    username: wateruser
    password: itcast
    driver-class-name: oracle.jdbc.driver.OracleDriver

logging:
  config: classpath:log/logback.xml
pagehelper:
  helper-dialect: oracle
  reasonable: true
  offset-as-page-num: true
  row-bounds-with-count: true

  #server:
  #  servlet:
  #    context-path: /api

minio:
  endpoint: http://192.168.146.5:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: tdms
