#mapper:
#  mappers:
#    - tk.mybatis.mapper.common.Mapper
#  notEmpty: true
#  ORDER: BEFORE

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xxxx.mappertest
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置Oracle数据库
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.90.10:1521:orcl
    username: wateruser
    password: itcast
    driver-class-name: oracle.jdbc.driver.OracleDriver

logging:
  config: classpath:log/logback.xml